###
# Connexion avec token
POST http://localhost:3000/auth HTTP/1.1
content-type: application/json

{
    "name":"alex", 
    "password": "alex"
}

###
# Connexion avec token
POST http://localhost:3000/auth HTTP/1.1
content-type: application/json

{
    "name":"alex", 
    "password": "al"
}

